### ISSUE TITLE
Tailwind CSS integration

### ISSUE THREAD

**Issue by ambanikousik** [simolus3/zap#11]
Do you have any plan to make a way of inegrating Tailwind Css to Zap ?

**Comment by simolus3** [comment]
In general, you can use any CSS framework by just putting the CSS/Sass/SCSS source files in a Dart package and importing it just like you would with Dart sources.

Tailwind is special because they compile a CSS file based on the classes you actually use. This requires special logic in the build system, and we can't easily replicate that in Dart (since their build tooling is written in JS of course). If you have a precompiled tailwind with the classes you use ready as a CSS file, you can include it with `@import` or `@use` in a component's CSS. But there won't be a way to integrate Tailwind's build system into zap.
