### ISSUE TITLE
May I ask, has the development slowed down, i wanted to use zap, in production, thanks

### ISSUE THREAD

**Issue by gintominto5329** [simolus3/zap#19]
Please read the title

**Comment by simolus3** [comment]
Hi, and thanks for your interest. It's true that the development has slowed down somewhat, but that's because I mostly wrote zap for my own projects and it does what it's supposed to do. Essentially, I keep it updated to work with the latest Dart version, but I don't have any plans to work on larger new features at the moment.

If there is a community interest in new features that could definitely change - this project isn't discontinued. It has just reached a state that works well for what I had in mind.

**Comment by gintominto5329** [comment]
Actually we needed a framework urgently, 

So may I ask, among [Jaspr](https://pub.dev/packages/jaspr), [Dawn](https://pub.dev/packages/dawn), [rad](https://pub.dev/packages/rad), 
- Which one would you recommend for a production website(not app),
- If you have to create a web(-site) project, which one would you choose,

thanks

**Comment by simolus3** [comment]
I haven't used any of them yet so I can't give advice. I've heard good things about Jaspr.
