### ISSUE TITLE
Watchables

### ISSUE THREAD

**Issue by mjablecnik** [simolus3/zap#7]
Hello, thank you for create Zap as very nice Dart alternative of Svelte. :)

I have one question:
When I saw some examples, I didn't understand what means watchables.: https://simonbinder.eu/zap/examples/#watch-write
But after some time of thinking I discovered that it is same as Store in Svelte.

My question is:
Why are you not keeping same naming convention what it is in Svelte?
I think that when Zap is developed following the Svelte pattern so it can be easy for Svelte developers (like me) understand Zap and move or understand everything in Zap when we will keep the same naming convention.

So I think that `Store` can be better name than `Watchables` in docs.
What do you think about it?

**Comment by simolus3** [comment]
Watchables and stores a bit different I think. Overall, I think watchables fit better into a Dart framework because Dart is already largely built ontop of streams (unlike JavaScript, which typically uses event callbacks). So Svelte essentially had to define a stream interface with stores and we're able to just use the Dart class that already exists for them.

Another thing is that it's a bit complicated to inject the implicit `$store` variables in a way that the analyzer would be able to pick them up (or at least I couldn't find a good way to do that in Dart).

Finally, in the next zap version, you'll be able to nest `watch()` calls and use them everywhere, so you could do e.g.

```
<script>
  // some external definitions, assume they exist
  Watchable<Location> get currentLocation;
  Watchable<Weather> weatherIn(Location location);
</script>

The current weather is { watch(weatherIn(watch(currentLocation))) }
```

I'm not sure if this is that easily possible with the stores API from svelte.

Clearly the docs should be better at pointing out that a `Watchable` is similar to a `Store` from svelte (and I'm not entirely opposed to renaming them for consistency). But even though zap is clearly inspired by svelte, I want to do my own thing here :)  I want Zap to be a great Dart framework, and not just a direct port bringing JS-style APIs to Dart.

**Comment by simolus3** [comment]
I've expanded the docs to point our more similarities with Svelte stores in 47cb7cee575ae539a339a5242b6ce656e7ff7f33.
